### ISSUE TITLE
Question on how it works

### ISSUE THREAD

**Issue by httpete** [trygve-lie/esbuild-plugin-import-map#33]
Hi,

Your plugin is so close to what I need, but I can't seem to make it work right. I have an importmap and I really just want to rewrite e.g.

import {useState} from 'react';

to

import {useState} from '../web_modules/react';

So I have a list of third party imports and I just want to use relative imports. Any thoughts? Thank you

**Comment by digitalsadhu** [comment]
Hey! 

So I understand, what do you expect the final url to look like? Do you mean you want the relative url to be resolved against the location of the asset server? Or do you want the final output to be relative? What have you tried so far?

**Comment by httpete** [comment]
Hello thank you for your reply,

I learned that without the bundle: true option set in esbuild, your plugin doesn't work. With it, it works PERFECTLY! 
That might be nice to document more clearly.
Your plugin is my exact use case. Now that snowpack is dying, I needed a pure esbuild solution. Combined with esinstall, and your import map plugin, you can essentially get rid of snowpack. Big thanks!

**Comment by digitalsadhu** [comment]
Great! No problem. 
if you have time, feel free to paste in your final working setup here in case it’s useful for others.

**Comment by httpete** [comment]
This solution really has 3 simple scripts, and functionally replaces snowpack and dev server.

add this to a file scripts/build.mjs, and add it to package.json / scripts as 

{ scripts:     "build": "node scripts/build.mjs" }

I have another script which uses esinstall, scripts/install.mjs. Do that in postinstall: "node scripts/install.mjs"
You can improve this by reading package.json / dependencies and loading the array dynamically. 

//install.mjs
`import { install } from 'esinstall';
await install(['react', 'react-dom', '@mui/material', '@emotion/react', '@emotion/styled'], {
    dest: 'dist/web_modules'
  });`

Note here how bundle is true. Then the import map works perfectly as an absolute url. It will work at every level of depth. That was the trick - once you understand esm loads urls according to the base / rules of the page like every other url on a web page.

//build.mjs
`import esbuild from 'esbuild';
import * as importMap from "esbuild-plugin-import-map";
import { globPlugin } from 'esbuild-plugin-glob';
import fs from 'fs';

const map = JSON.parse(fs.readFileSync('./dist/web_modules/import-map.json',
            {encoding:'utf8', flag:'r'}));

for (var i in map.imports){
    map.imports[i] = map.imports[i].replace('./', '/web_modules/');
}

importMap.load(map);

esbuild.build({
    entryPoints: ['src/**/*.tsx'],
    bundle: true,
    format: 'esm',
    inject: ['./react-shim.js'],
    minify: false,
    sourcemap: true,
    watch: false,
    target: 'es2020',
    plugins: [globPlugin(), importMap.plugin()],
    outdir: 'dist',
}).
then(() => { 
    import('./serve.mjs')
})
.catch(() => process.exit(1))`

//serve.mjs
`import liveServer from "live-server"
 
var params = {
    port: 8181, // Set the server port. Defaults to 8080.
    root: "dist", // Set root directory that's being served. Defaults to cwd.
    logLevel: 2, // 0 = errors only, 1 = some, 2 = lots
    open: false
};
liveServer.start(params);`
